2019-09-28 21:17:48,074 [MainThread: 4781032896]/Users/chengyinliu/WeChatProjects/backend/ops/logdemo.py:logdemo:11 INFO - hello logging
2019-09-28 21:19:04,730 [MainThread: 4706653632]/Users/chengyinliu/WeChatProjects/backend/ops/logdemo.py:logdemo:11 INFO - hello logging
2019-09-28 21:19:04,731 [MainThread: 4706653632]/Users/chengyinliu/WeChatProjects/backend/ops/logdemo.py:logdemo:12 DEBUG - hello debug log
2019-09-28 21:19:27,495 [MainThread: 4699813312]/Users/chengyinliu/WeChatProjects/backend/ops/logdemo.py:logdemo:11 INFO - hello logging
2019-09-28 21:19:27,496 [MainThread: 4699813312]/Users/chengyinliu/WeChatProjects/backend/ops/logdemo.py:logdemo:12 DEBUG - hello debug log
2019-09-29 17:46:49,756 [MainThread: 4590572992]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-09-29 17:46:49,757 [MainThread: 4590572992]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:46:49,757 [MainThread: 4590572992]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-09-29 17:46:49,778 [MainThread: 4590572992]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:46:49,780 [MainThread: 4590572992]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.002) SHOW FULL TABLES; args=None
2019-09-29 17:46:49,783 [MainThread: 4590572992]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-09-29 17:46:56,599 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-09-29 17:46:56,600 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:46:56,600 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@sql_mode; args=None
2019-09-29 17:46:56,747 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-09-29 17:46:56,764 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SHOW FULL TABLES; args=None
2019-09-29 17:46:56,766 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-09-29 17:46:56,767 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SHOW FULL TABLES; args=None
2019-09-29 17:46:56,767 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-09-29 17:46:56,798 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SHOW FULL TABLES; args=None
2019-09-29 17:46:56,799 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SHOW FULL TABLES; args=None
2019-09-29 17:46:56,800 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-09-29 17:46:56,801 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'admin' AND `django_content_type`.`model` = 'logentry'); args=('admin', 'logentry')
2019-09-29 17:46:56,804 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (1) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(1,)
2019-09-29 17:46:56,805 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'admin'; args=('admin',)
2019-09-29 17:46:56,807 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'auth' AND `django_content_type`.`model` = 'permission'); args=('auth', 'permission')
2019-09-29 17:46:56,808 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'auth' AND `django_content_type`.`model` = 'group'); args=('auth', 'group')
2019-09-29 17:46:56,809 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'auth' AND `django_content_type`.`model` = 'user'); args=('auth', 'user')
2019-09-29 17:46:56,813 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.002) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (2, 3, 4) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(2, 3, 4)
2019-09-29 17:46:56,814 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'auth'; args=('auth',)
2019-09-29 17:46:56,815 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'contenttypes' AND `django_content_type`.`model` = 'contenttype'); args=('contenttypes', 'contenttype')
2019-09-29 17:46:56,816 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (5) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(5,)
2019-09-29 17:46:56,817 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'contenttypes'; args=('contenttypes',)
2019-09-29 17:46:56,818 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'sessions' AND `django_content_type`.`model` = 'session'); args=('sessions', 'session')
2019-09-29 17:46:56,819 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (6) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(6,)
2019-09-29 17:46:56,819 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'sessions'; args=('sessions',)
2019-09-29 17:46:56,821 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'apis' AND `django_content_type`.`model` = 'app'); args=('apis', 'app')
2019-09-29 17:46:56,823 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (8) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(8,)
2019-09-29 17:46:56,823 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'apis'; args=('apis',)
2019-09-29 17:46:56,824 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'authorization' AND `django_content_type`.`model` = 'user'); args=('authorization', 'user')
2019-09-29 17:46:56,825 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (7) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(7,)
2019-09-29 17:46:56,826 [MainThread: 4643403200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'authorization'; args=('authorization',)
2019-09-29 17:52:23,555 [MainThread: 4693341632]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-09-29 17:52:23,556 [MainThread: 4693341632]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:52:23,556 [MainThread: 4693341632]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-09-29 17:52:23,583 [MainThread: 4693341632]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:52:23,586 [MainThread: 4693341632]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.002) SHOW FULL TABLES; args=None
2019-09-29 17:52:23,589 [MainThread: 4693341632]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-09-29 17:52:31,001 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-09-29 17:52:31,002 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:52:31,003 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@sql_mode; args=None
2019-09-29 17:52:31,223 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-09-29 17:52:31,247 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SHOW FULL TABLES; args=None
2019-09-29 17:52:31,250 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-09-29 17:52:31,251 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SHOW FULL TABLES; args=None
2019-09-29 17:52:31,251 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-09-29 17:52:31,302 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SHOW FULL TABLES; args=None
2019-09-29 17:52:31,303 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SHOW FULL TABLES; args=None
2019-09-29 17:52:31,305 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-09-29 17:52:31,308 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'admin' AND `django_content_type`.`model` = 'logentry'); args=('admin', 'logentry')
2019-09-29 17:52:31,310 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (1) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(1,)
2019-09-29 17:52:31,312 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'admin'; args=('admin',)
2019-09-29 17:52:31,313 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'auth' AND `django_content_type`.`model` = 'permission'); args=('auth', 'permission')
2019-09-29 17:52:31,315 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'auth' AND `django_content_type`.`model` = 'group'); args=('auth', 'group')
2019-09-29 17:52:31,316 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'auth' AND `django_content_type`.`model` = 'user'); args=('auth', 'user')
2019-09-29 17:52:31,318 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (2, 3, 4) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(2, 3, 4)
2019-09-29 17:52:31,319 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'auth'; args=('auth',)
2019-09-29 17:52:31,321 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'contenttypes' AND `django_content_type`.`model` = 'contenttype'); args=('contenttypes', 'contenttype')
2019-09-29 17:52:31,323 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (5) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(5,)
2019-09-29 17:52:31,325 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'contenttypes'; args=('contenttypes',)
2019-09-29 17:52:31,326 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'sessions' AND `django_content_type`.`model` = 'session'); args=('sessions', 'session')
2019-09-29 17:52:31,329 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (6) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(6,)
2019-09-29 17:52:31,330 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'sessions'; args=('sessions',)
2019-09-29 17:52:31,331 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'apis' AND `django_content_type`.`model` = 'app'); args=('apis', 'app')
2019-09-29 17:52:31,333 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (8) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(8,)
2019-09-29 17:52:31,334 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'apis'; args=('apis',)
2019-09-29 17:52:31,335 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`app_label` = 'authorization' AND `django_content_type`.`model` = 'user'); args=('authorization', 'user')
2019-09-29 17:52:31,337 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (7) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(7,)
2019-09-29 17:52:31,339 [MainThread: 4484064704]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'authorization'; args=('authorization',)
2019-09-29 17:54:37,344 [Dummy-1: 123145558835200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-09-29 17:54:37,345 [Dummy-1: 123145558835200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:54:37,345 [Dummy-1: 123145558835200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-09-29 17:54:37,367 [Dummy-1: 123145558835200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:54:37,368 [Dummy-1: 123145558835200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SHOW FULL TABLES; args=None
2019-09-29 17:54:37,371 [Dummy-1: 123145558835200]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-09-29 17:54:39,939 [Thread-2: 123145564090368]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-09-29 17:54:39,940 [Thread-2: 123145564090368]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:54:39,940 [Thread-2: 123145564090368]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-09-29 17:54:39,940 [Thread-2: 123145564090368]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:54:39,941 [Thread-2: 123145564090368]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-09-29 17:54:39.938151' AND `django_session`.`session_key` = '5pkv6zv5vmpdcsufdo95sb4oabr956n1'); args=('2019-09-29 17:54:39.938151', '5pkv6zv5vmpdcsufdo95sb4oabr956n1')
2019-09-29 17:54:39,942 [Thread-2: 123145564090368]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-09-29 17:54:39,965 [Thread-2: 123145564090368]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x1078db598>>, 'request': <WSGIRequest: GET '/admin/'>, 'user': <SimpleLazyObject: <User: chengyinliu>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x107953a20>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1078a7828>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'site_title': 'Django site admin', 'site_header': 'Django administration', 'site_url': '/', 'has_permission': True, 'available_apps': [{'name': 'Apis', 'app_label': 'apis', 'app_url': '/admin/apis/', 'has_module_perms': True, 'models': [{'name': 'Apps', 'object_name': 'App', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/apis/app/', 'add_url': '/admin/apis/app/add/'}]}, {'name': 'Authentication and Authorization', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Groups', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/user/', 'add_url': '/admin/auth/user/add/'}]}, {'name': 'Authorization', 'app_label': 'authorization', 'app_url': '/admin/authorization/', 'has_module_perms': True, 'models': [{'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/authorization/user/', 'add_url': '/admin/authorization/user/add/'}]}], 'title': 'Site administration', 'app_list': [{'name': 'Apis', 'app_label': 'apis', 'app_url': '/admin/apis/', 'has_module_perms': True, 'models': [{'name': 'Apps', 'object_name': 'App', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/apis/app/', 'add_url': '/admin/apis/app/add/'}]}, {'name': 'Authentication and Authorization', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Groups', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/user/', 'add_url': '/admin/auth/user/add/'}]}, {'name': 'Authorization', 'app_label': 'authorization', 'app_url': '/admin/authorization/', 'has_module_perms': True, 'models': [{'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/authorization/user/', 'add_url': '/admin/authorization/user/add/'}]}], 'LANGUAGE_CODE': 'en-us', 'LANGUAGE_BIDI': False}]
2019-09-29 17:54:39,969 [Thread-2: 123145564090368]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x1078db598>>, 'request': <WSGIRequest: GET '/admin/'>, 'user': <SimpleLazyObject: <User: chengyinliu>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x107953a20>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x1078a7828>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'site_title': 'Django site admin', 'site_header': 'Django administration', 'site_url': '/', 'has_permission': True, 'available_apps': [{'name': 'Apis', 'app_label': 'apis', 'app_url': '/admin/apis/', 'has_module_perms': True, 'models': [{'name': 'Apps', 'object_name': 'App', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/apis/app/', 'add_url': '/admin/apis/app/add/'}]}, {'name': 'Authentication and Authorization', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Groups', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/user/', 'add_url': '/admin/auth/user/add/'}]}, {'name': 'Authorization', 'app_label': 'authorization', 'app_url': '/admin/authorization/', 'has_module_perms': True, 'models': [{'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/authorization/user/', 'add_url': '/admin/authorization/user/add/'}]}], 'title': 'Site administration', 'app_list': [{'name': 'Apis', 'app_label': 'apis', 'app_url': '/admin/apis/', 'has_module_perms': True, 'models': [{'name': 'Apps', 'object_name': 'App', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/apis/app/', 'add_url': '/admin/apis/app/add/'}]}, {'name': 'Authentication and Authorization', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Groups', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/user/', 'add_url': '/admin/auth/user/add/'}]}, {'name': 'Authorization', 'app_label': 'authorization', 'app_url': '/admin/authorization/', 'has_module_perms': True, 'models': [{'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/authorization/user/', 'add_url': '/admin/authorization/user/add/'}]}], 'LANGUAGE_CODE': 'en-us', 'LANGUAGE_BIDI': False}]
2019-09-29 17:54:39,974 [Thread-2: 123145564090368]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.002) SELECT `django_admin_log`.`id`, `django_admin_log`.`action_time`, `django_admin_log`.`user_id`, `django_admin_log`.`content_type_id`, `django_admin_log`.`object_id`, `django_admin_log`.`object_repr`, `django_admin_log`.`action_flag`, `django_admin_log`.`change_message`, `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_admin_log` INNER JOIN `auth_user` ON (`django_admin_log`.`user_id` = `auth_user`.`id`) LEFT OUTER JOIN `django_content_type` ON (`django_admin_log`.`content_type_id` = `django_content_type`.`id`) WHERE `django_admin_log`.`user_id` = 1 ORDER BY `django_admin_log`.`action_time` DESC LIMIT 10; args=(1,)
2019-09-29 17:54:39,975 [Thread-2: 123145564090368]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /admin/ HTTP/1.1" 200 4284
2019-09-29 17:54:54,546 [Dummy-1: 123145563303936]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-09-29 17:54:54,547 [Dummy-1: 123145563303936]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:54:54,547 [Dummy-1: 123145563303936]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-09-29 17:54:54,569 [Dummy-1: 123145563303936]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:54:54,570 [Dummy-1: 123145563303936]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SHOW FULL TABLES; args=None
2019-09-29 17:54:54,572 [Dummy-1: 123145563303936]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-09-29 17:55:05,394 [Dummy-1: 123145417588736]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-09-29 17:55:05,395 [Dummy-1: 123145417588736]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:55:05,396 [Dummy-1: 123145417588736]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-09-29 17:55:05,415 [Dummy-1: 123145417588736]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:55:05,416 [Dummy-1: 123145417588736]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SHOW FULL TABLES; args=None
2019-09-29 17:55:05,418 [Dummy-1: 123145417588736]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-09-29 17:55:07,114 [Dummy-1: 123145424945152]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-09-29 17:55:07,115 [Dummy-1: 123145424945152]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:55:07,115 [Dummy-1: 123145424945152]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-09-29 17:55:07,136 [Dummy-1: 123145424945152]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:55:07,136 [Dummy-1: 123145424945152]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SHOW FULL TABLES; args=None
2019-09-29 17:55:07,139 [Dummy-1: 123145424945152]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2019-09-29 17:55:07,943 [Thread-2: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-09-29 17:55:07,943 [Thread-2: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:55:07,943 [Thread-2: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-09-29 17:55:07,944 [Thread-2: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:55:07,945 [Thread-2: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-09-29 17:55:07.941922' AND `django_session`.`session_key` = '5pkv6zv5vmpdcsufdo95sb4oabr956n1'); args=('2019-09-29 17:55:07.941922', '5pkv6zv5vmpdcsufdo95sb4oabr956n1')
2019-09-29 17:55:07,946 [Thread-2: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-09-29 17:55:07,969 [Thread-2: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x10a610488>>, 'request': <WSGIRequest: GET '/admin/'>, 'user': <SimpleLazyObject: <User: chengyinliu>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10a688940>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x109e01be0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'site_title': 'Django site admin', 'site_header': 'Django administration', 'site_url': '/', 'has_permission': True, 'available_apps': [{'name': 'Apis', 'app_label': 'apis', 'app_url': '/admin/apis/', 'has_module_perms': True, 'models': [{'name': 'Apps', 'object_name': 'App', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/apis/app/', 'add_url': '/admin/apis/app/add/'}]}, {'name': 'Authentication and Authorization', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Groups', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/user/', 'add_url': '/admin/auth/user/add/'}]}, {'name': 'Authorization', 'app_label': 'authorization', 'app_url': '/admin/authorization/', 'has_module_perms': True, 'models': [{'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/authorization/user/', 'add_url': '/admin/authorization/user/add/'}]}], 'title': 'Site administration', 'app_list': [{'name': 'Apis', 'app_label': 'apis', 'app_url': '/admin/apis/', 'has_module_perms': True, 'models': [{'name': 'Apps', 'object_name': 'App', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/apis/app/', 'add_url': '/admin/apis/app/add/'}]}, {'name': 'Authentication and Authorization', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Groups', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/user/', 'add_url': '/admin/auth/user/add/'}]}, {'name': 'Authorization', 'app_label': 'authorization', 'app_url': '/admin/authorization/', 'has_module_perms': True, 'models': [{'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/authorization/user/', 'add_url': '/admin/authorization/user/add/'}]}], 'LANGUAGE_CODE': 'en-us', 'LANGUAGE_BIDI': False}]
2019-09-29 17:55:07,972 [Thread-2: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x10a610488>>, 'request': <WSGIRequest: GET '/admin/'>, 'user': <SimpleLazyObject: <User: chengyinliu>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x10a688940>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x109e01be0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'site_title': 'Django site admin', 'site_header': 'Django administration', 'site_url': '/', 'has_permission': True, 'available_apps': [{'name': 'Apis', 'app_label': 'apis', 'app_url': '/admin/apis/', 'has_module_perms': True, 'models': [{'name': 'Apps', 'object_name': 'App', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/apis/app/', 'add_url': '/admin/apis/app/add/'}]}, {'name': 'Authentication and Authorization', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Groups', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/user/', 'add_url': '/admin/auth/user/add/'}]}, {'name': 'Authorization', 'app_label': 'authorization', 'app_url': '/admin/authorization/', 'has_module_perms': True, 'models': [{'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/authorization/user/', 'add_url': '/admin/authorization/user/add/'}]}], 'title': 'Site administration', 'app_list': [{'name': 'Apis', 'app_label': 'apis', 'app_url': '/admin/apis/', 'has_module_perms': True, 'models': [{'name': 'Apps', 'object_name': 'App', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/apis/app/', 'add_url': '/admin/apis/app/add/'}]}, {'name': 'Authentication and Authorization', 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True, 'models': [{'name': 'Groups', 'object_name': 'Group', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/group/', 'add_url': '/admin/auth/group/add/'}, {'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/auth/user/', 'add_url': '/admin/auth/user/add/'}]}, {'name': 'Authorization', 'app_label': 'authorization', 'app_url': '/admin/authorization/', 'has_module_perms': True, 'models': [{'name': 'Users', 'object_name': 'User', 'perms': {'add': True, 'change': True, 'delete': True}, 'admin_url': '/admin/authorization/user/', 'add_url': '/admin/authorization/user/add/'}]}], 'LANGUAGE_CODE': 'en-us', 'LANGUAGE_BIDI': False}]
2019-09-29 17:55:07,976 [Thread-2: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_admin_log`.`id`, `django_admin_log`.`action_time`, `django_admin_log`.`user_id`, `django_admin_log`.`content_type_id`, `django_admin_log`.`object_id`, `django_admin_log`.`object_repr`, `django_admin_log`.`action_flag`, `django_admin_log`.`change_message`, `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_admin_log` INNER JOIN `auth_user` ON (`django_admin_log`.`user_id` = `auth_user`.`id`) LEFT OUTER JOIN `django_content_type` ON (`django_admin_log`.`content_type_id` = `django_content_type`.`id`) WHERE `django_admin_log`.`user_id` = 1 ORDER BY `django_admin_log`.`action_time` DESC LIMIT 10; args=(1,)
2019-09-29 17:55:07,977 [Thread-2: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /admin/ HTTP/1.1" 200 4284
2019-09-29 17:55:11,516 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-09-29 17:55:11,516 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:55:11,516 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-09-29 17:55:11,517 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:55:11,518 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-09-29 17:55:11.514657' AND `django_session`.`session_key` = '5pkv6zv5vmpdcsufdo95sb4oabr956n1'); args=('2019-09-29 17:55:11.514657', '5pkv6zv5vmpdcsufdo95sb4oabr956n1')
2019-09-29 17:55:11,519 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-09-29 17:55:11,522 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.002) SELECT COUNT(*) AS `__count` FROM `apis_app`; args=()
2019-09-29 17:55:11,523 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT COUNT(*) AS `__count` FROM `apis_app`; args=()
2019-09-29 17:55:11,524 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `apis_app`.`appid`, `apis_app`.`category`, `apis_app`.`application`, `apis_app`.`name`, `apis_app`.`publish_date`, `apis_app`.`url`, `apis_app`.`desc` FROM `apis_app` ORDER BY `apis_app`.`appid` DESC; args=()
2019-09-29 17:55:11,533 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [errors] in None
2019-09-29 17:55:11,536 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 841, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'show'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [show] in [{'True': True, 'False': False, 'None': None, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x10a6c4ea0>>}]
2019-09-29 17:55:11,536 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_multipart'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_multipart] in None
2019-09-29 17:55:11,556 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in None
2019-09-29 17:55:11,556 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in None
2019-09-29 17:55:11,557 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in None
2019-09-29 17:55:11,557 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in None
2019-09-29 17:55:11,557 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'non_field_errors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [non_field_errors] in None
2019-09-29 17:55:11,559 [Thread-3: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /admin/apis/app/ HTTP/1.1" 200 7082
2019-09-29 17:55:11,568 [Thread-4: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2019-09-29 17:55:11,569 [Thread-4: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:55:11,569 [Thread-4: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT VERSION(); args=None
2019-09-29 17:55:11,570 [Thread-4: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
2019-09-29 17:55:11,570 [Thread-4: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`expire_date` > '2019-09-29 17:55:11.567212' AND `django_session`.`session_key` = '5pkv6zv5vmpdcsufdo95sb4oabr956n1'); args=('2019-09-29 17:55:11.567212', '5pkv6zv5vmpdcsufdo95sb4oabr956n1')
2019-09-29 17:55:11,572 [Thread-4: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/db/backends/utils.py:execute:111 DEBUG - (0.000) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 1; args=(1,)
2019-09-29 17:55:11,575 [Thread-4: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 INFO - "GET /admin/jsi18n/ HTTP/1.1" 200 3185
2019-09-29 17:55:11,673 [Thread-5: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'backend.version_1_0' from '/Users/chengyinliu/WeChatProjects/backend/backend/version_1_0.py'> (None:None) 'api/v1.0/'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <URLPattern list> (admin:admin) 'admin/'>
2019-09-29 17:55:11,674 [Thread-5: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py:_resolve_lookup:878 DEBUG - Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/urls/resolvers.py", line 527, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'tried': [[<URLResolver <URLPattern list> (admin:admin) 'admin/'>], [<URLResolver <module 'backend.version_1_0' from '/Users/chengyinliu/WeChatProjects/backend/backend/version_1_0.py'> (None:None) 'api/v1.0/'>]], 'path': 'favicon.ico'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 835, in _resolve_lookup
    current = current[bit]
TypeError: 'URLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'URLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 849, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/template/base.py", line 856, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in <URLResolver <module 'backend.version_1_0' from '/Users/chengyinliu/WeChatProjects/backend/backend/version_1_0.py'> (None:None) 'api/v1.0/'>
2019-09-29 17:55:11,675 [Thread-5: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/handlers/base.py:get_response:93 WARNING - Not Found: /favicon.ico
2019-09-29 17:55:11,675 [Thread-5: 123145430200320]/Users/chengyinliu/anaconda3/lib/python3.7/site-packages/django/core/servers/basehttp.py:log_message:124 WARNING - "GET /favicon.ico HTTP/1.1" 404 2082
